### ISSUE TITLE
Investigate automatic rescaling strategies in Flink via Flink's REST API

### ISSUE THREAD

**Issue by ankushs92** [NebulaStream-Optimizer/ml-for-optimizer#18]
For starters : 

https://cwiki.apache.org/confluence/display/FLINK/FLIP-8%3A+Rescalable+Non-Partitioned+State

https://docs.google.com/document/d/1G1OS1z3xEBOrYD4wSu-LuBCyPUWyFd9l3T9WyssQ63w/edit#

**Comment by iprapas** [comment]
Basically the rescaling API doesn't work and has been therefore disabled https://issues.apache.org/jira/browse/FLINK-12312
